CREATE TABLE IF NOT EXISTS usuarios (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(150) NOT NULL,
  email VARCHAR(254) NOT NULL,
  senha_hash VARCHAR(255) NOT NULL,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS profissionais (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  usuario_id BIGINT UNSIGNED NOT NULL,
  registro_profissional VARCHAR(80) NOT NULL,
  especialidade VARCHAR(120) NOT NULL,
  CONSTRAINT fk_profissional_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS convenios (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nome_convenio VARCHAR(150) NOT NULL,
  ativo BOOLEAN NOT NULL DEFAULT TRUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS pacientes (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nome_completo VARCHAR(180) NOT NULL,
  celular VARCHAR(20) NOT NULL,
  convenio_id BIGINT UNSIGNED NULL,
  numero_carteirinha VARCHAR(80) NULL,
  descricao_problema TEXT NULL,
  profissao VARCHAR(120) NULL,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_paciente_convenio FOREIGN KEY (convenio_id) REFERENCES convenios(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS agendamentos (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  paciente_id BIGINT UNSIGNED NOT NULL,
  profissional_id BIGINT UNSIGNED NOT NULL,
  data_hora DATETIME NOT NULL,
  tipo_consulta VARCHAR(120) NOT NULL DEFAULT 'Consulta Padrão',
  observacoes TEXT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'Agendado',
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_agendamento_paciente FOREIGN KEY (paciente_id) REFERENCES pacientes(id),
  CONSTRAINT fk_agendamento_profissional FOREIGN KEY (profissional_id) REFERENCES profissionais(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS atendimentos (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  agendamento_id BIGINT UNSIGNED NOT NULL,
  data_atendimento TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  evolucao_clinica TEXT NULL,
  procedimentos_realizados TEXT NULL,
  CONSTRAINT fk_atendimento_agendamento FOREIGN KEY (agendamento_id) REFERENCES agendamentos(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS configuracoes_clinica (
  id TINYINT UNSIGNED PRIMARY KEY,
  nome_clinica VARCHAR(180) NOT NULL,
  cnpj VARCHAR(20) NOT NULL DEFAULT '',
  telefone VARCHAR(20) NOT NULL DEFAULT '',
  email VARCHAR(254) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS mensagens_padrao (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  titulo VARCHAR(150) NOT NULL,
  mensagem VARCHAR(2000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS whatsapp_eventos (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  message_id VARCHAR(191) NOT NULL,
  numero VARCHAR(30) NOT NULL,
  texto VARCHAR(2000) NOT NULL,
  status ENUM('pendente', 'processando', 'concluido', 'falhou') NOT NULL DEFAULT 'pendente',
  tentativas TINYINT UNSIGNED NOT NULL DEFAULT 0,
  ultimo_erro VARCHAR(1000) NULL,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
